<root> ::= <sequence> | <selector>
<sequence> ::= Sequence(<ppa>)| [Sequence]<root><root>[/Sequence]
[Sequence]<sequence><root>[/Sequence]
<selector> ::= [Selector]<ppa>[/Selector]|[Selector]<root><root>[/Selector]
[Selector]<selector><root>[/Selector]
<ppa> ::= [Selector]<postconditions><ppasequence>[/Selector]
<postconditions> ::= <SuccessNode> | <ppa> |[Sequence]<postcondition>[/Sequence]
<postcondition> ::= <postcondition>[PostCnd]<postconditiont>
[/PostCnd]|[PostCnd]<postconditiont>[/PostCnd]
<postconditiont> ::= NeighbourObjects <objects>|NeighbourObjects <sobjects>|IsCarrying <dobjects>
NeighbourObjects <dobjects>|DidAvoidedObj <sobjects>|IsVisitedBefore <sobjects>
<ppasequence> ::= [Sequence]<preconditions>[Act]<action> [/Act][/Sequence]|[Sequence]<constraints>
[Act]<action>[/Act][/Sequence]|[Sequence]<preconditions><constraints> [Act]<action>[/Act][/Sequence]
<preconditions> ::= [Sequence]<precondition>[/Sequence]
<precondition> ::= <precondition>[PreCnd]<preconditiont> [/PreCnd]| [PreCnd]<preconditiont>[/PreCnd]
<preconditiont> ::= IsDropable <sobjects>|NeighbourObjects <objects>|IsVisitedBefore <sobjects>|
NeighbourObjects <objects> invert|IsVisitedBefore <sobjects> invert|
IsCarrying <dobjects>|IsCarrying <dobjects> invert
<constraints> ::= [Sequence]<constraint>[/Sequence]
<constraint> ::= <constraint>[Cnstr]<constraintt>[/Cnstr]|[Cnstr]<constraintt>[/Cnstr]
<constraintt> ::= CanMove|IsCarryable <dobjects>| IsDropable <sobjects>
<action> ::= MoveTowards <sobjects>|Explore|
CompositeSingleCarry <dobjects>|CompositeDrop <dobjects>| MoveAway <sobjects>
<objects> ::= <sobjects>|<dobjects>
<sobjects> ::= Hub|Sites
<dobjects> ::= Food|Debris
<SuccessNode> :: = [PostCnd]DummyNode[/PostCnd]